{% set name = "jupyterlab-pullrequests" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bb7b89c905e23becc8063e426c7e2195169dc39d65cb5c5ed7e75fada8d445a2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - nodejs
    - python >=3.6,<4.0
    - pip
    - jupyterlab >=2.0.0,<3.0.0
    - jupyter-packaging >=0.4.0,<0.5.0
    - setuptools >=40.8.0
    - wheel
  run:
    - python >=3.6,<4.0
    - jupyterlab >=2.0.0,<3.0.0
    - jupyterlab-git >=0.24.0,<0.30.0

test:
  requires:
    - pip
    - nodejs
  imports:
    - jupyterlab_pullrequests
  commands:
    - pip check
    - jupyter serverextension list 2>&1 | grep -ie "jupyterlab_pullrequests.*OK"
    - jupyter labextension list 2>&1 | grep -ie "@jupyterlab/pullrequests.*OK"
    - jupyter lab build

about:
  home: https://github.com/jupyterlab/pull-requests
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Manage Pull Requests in JupyterLab
  description: A JupyterLab extension for reviewing pull requests.

extra:
  recipe-maintainers:
    - fcollonval
